function out = findimgmaxima(imgin);
% function out = findimgmaxima(imgin)
% returns a binary mask of the same dimensions as imgin whose 1 values
% correspond to local maxima in imgin;
% AEC 11 Nov. 2009

out = zeros(size(imgin));
out(2:end-1,2:end-1) = (imgin(2:end-1,2:end-1) > imgin(1:end-2,2:end-1)) .* ...
    (imgin(2:end-1,2:end-1) > imgin(3:end,2:end-1)).*...
    (imgin(2:end-1,2:end-1) > imgin(2:end-1,1:end-2)).*...
    (imgin(2:end-1,2:end-1) > imgin(2:end-1,3:end)).*...
    (imgin(2:end-1,2:end-1) > imgin(1:end-2,1:end-2)) .* ...
    (imgin(2:end-1,2:end-1) > imgin(1:end-2,3:end)).*...
    (imgin(2:end-1,2:end-1) > imgin(3:end,1:end-2)).*...
    (imgin(2:end-1,2:end-1) > imgin(3:end,3:end));
