function outlinespots200120 = importfile1(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   OUTLINESPOTS200120 = IMPORTFILE1(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   OUTLINESPOTS200120 = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   outlinespots200120 = importfile1('1-4-3__outline_spots_200120.txt', 20, 2405);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/01/20 18:01:53

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 20;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
outlinespots200120 = table;
outlinespots200120.Pos_Y = cell2mat(raw(:, 1));
outlinespots200120.Pos_X = cell2mat(raw(:, 2));
outlinespots200120.Pos_Z = cell2mat(raw(:, 3));
outlinespots200120.AMP = cell2mat(raw(:, 4));
outlinespots200120.BGD = cell2mat(raw(:, 5));
outlinespots200120.RES = cell2mat(raw(:, 6));
outlinespots200120.SigmaX = cell2mat(raw(:, 7));
outlinespots200120.SigmaY = cell2mat(raw(:, 8));
outlinespots200120.SigmaZ = cell2mat(raw(:, 9));
outlinespots200120.Cent_Y = cell2mat(raw(:, 10));
outlinespots200120.Cent_X = cell2mat(raw(:, 11));
outlinespots200120.Cent_Z = cell2mat(raw(:, 12));
outlinespots200120.MuY = cell2mat(raw(:, 13));
outlinespots200120.MuX = cell2mat(raw(:, 14));
outlinespots200120.MuZ = cell2mat(raw(:, 15));
outlinespots200120.ITERY_det = cell2mat(raw(:, 16));
outlinespots200120.Y_det = cell2mat(raw(:, 17));
outlinespots200120.X_det = cell2mat(raw(:, 18));
outlinespots200120.Z_det = cell2mat(raw(:, 19));
outlinespots200120.Y_min = cell2mat(raw(:, 20));
outlinespots200120.Y_max = cell2mat(raw(:, 21));
outlinespots200120.X_min = cell2mat(raw(:, 22));
outlinespots200120.X_max = cell2mat(raw(:, 23));
outlinespots200120.Z_min = cell2mat(raw(:, 24));
outlinespots200120.Z_max = cell2mat(raw(:, 25));
outlinespots200120.INT_raw = cell2mat(raw(:, 26));
outlinespots200120.INT_filt = cell2mat(raw(:, 27));
outlinespots200120.SC_det = cell2mat(raw(:, 28));
outlinespots200120.SC_det_norm = cell2mat(raw(:, 29));
outlinespots200120.TH_det = cell2mat(raw(:, 30));
outlinespots200120.TH_fit = cell2mat(raw(:, 31));

