function dragonfly_write_settings_mat(app,fpath)
DAQ_waves = app.wavesToSave;
DAQ_channels = app.ni6343.outChannelsConfigData(:,1);
DAQ_data = app.ni6343.dataIn;

dmd_current_roi = app.dmdApp.current_rois;
dmd_mask_sequence = app.dmdApp.mask_sequence;
dmd_registration_data = app.dmdApp.registration_data;
dmd_mask_sequence_rois = app.dmdApp.mask_sequence_rois;
try
ref_ax = get(app.dmdApp.fig_mask_draw,'Children');
ref_c = get(ref_ax,'Children');
ref_im = ref_c(end).CData;
catch
    save(fullfile(fpath,'settings.mat'),...
    'DAQ_waves',...
    'DAQ_channels',...
    'dmd_current_roi',...
    'dmd_mask_sequence_rois',...
    'dmd_mask_sequence',...
    'dmd_registration_data','-v7.3')
    return
end
save(fullfile(fpath,'settings.mat'),...
    'DAQ_waves',...
    'DAQ_channels',...
    'DAQ_data',...
    'dmd_current_roi',...
    'dmd_mask_sequence_rois',...
    'dmd_mask_sequence',...
    'dmd_registration_data',...
    'ref_im','-v7.3')